name: Build and Deploy to ECR

on:
  push:
    branches:
      - main  # Triggers only on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials using GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t resume-app .
          docker tag resume-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

      # Step 5: Push the Docker image to ECR
      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
