name: Deploy Resume WebApp to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update the system
            sudo apt-get -y update

            # Install Apache2 if not already installed
            sudo apt-get install -y apache2

            # Ensure apache2 starts and is enabled
            sudo systemctl daemon-reload
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Ensure the target directory exists (e.g., /var/www/html)
            sudo mkdir -p /var/www/html

            # Remove existing contents of /var/www/html
            sudo rm -rf /var/www/html/*

            # Move the new files to /var/www/html
            sudo mv /home/ubuntu/github-action-practice11/* /var/www/html/

            # Set permissions for Apache to serve the content
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
