name: Deploy Resume WebApp to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the files
        uses: actions/checkout@v4

      # Ensure directory permissions and deployment
      - name: Ensure directory permissions and deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "--rsync-path='sudo rsync' --exclude=.git --exclude=.Dockerfile --exclude=.github"

      # Executing remote ssh commands using ssh key
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure the target directory exists and has the correct permissions
            sudo mkdir -p ${{ secrets.TARGET_DIR }}
            sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} ${{ secrets.TARGET_DIR }}
            sudo chmod -R 755 ${{ secrets.TARGET_DIR }}
            
            # Clean up existing files in /var/www/html and move new files
            sudo rm -rf /var/www/html/*
            cd ${{ secrets.TARGET_DIR }}
            sudo mv * /var/www/html

            # Set proper ownership and permissions for Apache
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Install Apache if not installed and start it
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl daemon-reload
            sudo systemctl start apache2
            sudo systemctl enable apache2



